drop index ESTA_FK;
drop index AEROPUERTO_PK;
drop index SALE_FK;
drop index SALEN_FK;
drop index AER_VUE_PK;
drop index AVION_PK;
drop index CLIENTE_PK;
drop index TIENE_FK;
drop index LUGAR_PK;
drop index PLAZA_PK;
drop index ASEGURA_FK;
drop index LO_RESERVAN_FK;
drop index RESERVA_PK;
drop index PAGA_FK;
drop index TARJETA_PK;
drop index PERTENECE_FK;
drop index ASIGNA_FK;
drop index ASGINA_FK;
drop index TARJETA_DE_EMBARQUE_PK;
drop index REALIZA_FK;
drop index VUELO_PK;
drop table AEROPUERTO cascade;
drop table AER_VUE cascade;
drop table AVION cascade;
drop table CLIENTE cascade;
drop table LUGAR cascade;
drop table PLAZA cascade;
drop table RESERVA cascade;
drop table TARJETA cascade;
drop table TARJETA_DE_EMBARQUE cascade;
drop table VUELO cascade;